stages:
  - build
  - deploy
  - production
  - release
variables:
#  CONTAINER_REGISTRY - container host
#  CI_PROJECT_NAMESPACE - folder
#  CI_PROJECT_NAME - name
#
#  Example
#  cr.yandex/crp4o7r2501stispash5/pet/api:gitlab-0603e482

  DOCKER_IMAGE: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DOCKER_IMAGE_LATEST: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest_test
  DOCKER_IMAGE_VERSION: $CONTAINER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:gitlab-$CI_COMMIT_SHORT_SHA
before_script:
  - apt update && apt install -y gettext-base jq

include: '.gitlab/*.yml'