build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
  script:
    - docker pull DOCKER_IMAGE_NIGHT || true
    - docker build . -t $DOCKER_IMAGE_BUILD --cache-from DOCKER_IMAGE_NIGHT
    - docker image tag $DOCKER_IMAGE_BUILD $DOCKER_IMAGE_NIGHT
    - docker image push $DOCKER_IMAGE_NIGHT
    - docker image push $DOCKER_IMAGE_BUILD
  only:
    refs:
      - master