apiVersion: v1
kind: Namespace
metadata:
  name: $PROJECT_NAMESPACE
---
kind: ConfigMap
metadata:
  name: $PROJECT_CONFIG_MAP
  namespace: $PROJECT_NAMESPACE
data:
  JWT_ACCESS_SECRET: jwt-secret-key
  JWT_REFRESH_SECRET: jwt-refresh-secret-key
  PORT: "4000"
  POSTGRES_DB: api
  POSTGRES_HOST: localhost
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: "5432"
  POSTGRES_USER: api
  NODE_ENV: develop