apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $PROJECT_NAME
  namespace: $PROJECT_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: $PROJECT_NAME
  namespace: $PROJECT_NAMESPACE
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: $PROJECT_PORT
      name: $PROJECT_NAME
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: $PROJECT_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  namespace: $PROJECT_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 2 # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      namespace: $PROJECT_NAMESPACE
      labels:
        app: $PROJECT_NAME
        apiVersion: $PROJECT_VERSION
    spec:
      containers:
        - name: $PROJECT_NAME
          image: $CONTAINER_IMAGE
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: $PROJECT_CONFIG_MAP
          ports:
            - containerPort: $PROJECT_PORT
        - name: postgres
          image: postgres
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: $PROJECT_CONFIG_MAP
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: $PROJECT_NAME