apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: pet
data:
  JWT_ACCESS_SECRET: jwt-secret-key
  JWT_REFRESH_SECRET: jwt-refresh-secret-key
  PGDATA: /var/lib/postgresql/data/pgdata
  PORT: "4000"
  POSTGRES_DB: api
  POSTGRES_HOST: api.pet.svc.cluster.local
  POSTGRES_PASSWORD: password
  POSTGRES_PORT: "5432"
  POSTGRES_USER: api
  NODE_ENV: develop